[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python -m venv /opt/venv", "/opt/venv/bin/pip install -r requirements.txt"]

[phases.build]
cmds = []

[variables]
PATH = "/opt/venv/bin:${PATH}"

[start]
cmd = "/opt/venv/bin/uvicorn server:app --host 0.0.0.0 --port $PORT"
